### ISSUE TITLE
Bad.

### ISSUE THREAD

**Issue by ghost** [vanybhops/limunxshortcutmakerig#1]
This is not a shortcut, this is a **symbolic** link. 

Get good, kid.

**Comment by vanybhops** [comment]
it says "ig" which means i guess
i guess =im not sure
tard

**Comment by fgets** [comment]
You are a noob at Linux.

**Comment by ghost** [comment]
You are a noob at Linux.

**Comment by vanybhops** [comment]
wa wa wawah she gave me what i wannah
